### ISSUE TITLE
Ada nemuvina backupu i public_html

### ISSUE THREAD

**Issue by justaspal** [hostinger/hubot#11]
Reikia updeitinti kad galetu muvinti, kazkas neveikia dabar. Taip pat butu super jei galetu muvinti backupa i kito accounto public_html.

**Comment by fordnox** [comment]
@specaz ar yra galimybe pamovinti backup is backup location home/username/public_html? jei ne tai reiktu sukurt toki action hosting-api

**Comment by specaz** [comment]
@fordnox Reiktu sukurti toki action

**Comment by justaspal** [comment]
Dar galetu sukurti downloadable linkus arba linka parsisiusti backupams

**Comment by zygintas** [comment]
@fordnox kas gali toki action sukurt hosting-api?

**Comment by fordnox** [comment]
viskas fixed su https://github.com/hostinger/hubot/pull/13
